# Generated by Django 2.2 on 2021-05-31 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210531_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='number_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Groups', verbose_name='Номер группы'),
        ),
    ]
