# Generated by Django 2.2 on 2021-05-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210531_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.TextField(blank=True, max_length=30, verbose_name='Имя студента'),
        ),
        migrations.AlterField(
            model_name='students',
            name='patronymic',
            field=models.TextField(blank=True, max_length=30, verbose_name='Отчество студента'),
        ),
        migrations.AlterField(
            model_name='students',
            name='surname',
            field=models.TextField(blank=True, max_length=30, verbose_name='Фамилия студента'),
        ),
    ]
